/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-126482-g903325e279-20260909"
#endif /* AVUTIL_FFVERSION_H */
