# ProtonVPN WireGuard Configuration
# Generated: 2026-09-09 17:49:23 +03
#
# Server Information:
# - Name: NL-FREE#156
# - Country: NL
# - City: Amsterdam
# - Tier: Free
# - Load: 84%
# - Score: 4.98
#
# Physical Server:
# - ID: fkBmrLlFxDMg1nw914xV7ZxGybApYoKy2KNObcgy9LAOPb2aD0t--Vu_HT0wEHSp9IRxq6fN6Ipwsu19IcCKrQ==
# - Entry IP: 185.107.56.22
#

[Interface]
PrivateKey = wG63SvCHddpn7Fi7lWjEAxQ+hwnTnrp0lxtxLapL8WQ=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
PublicKey = pUY22Gd3zhSoZZO6p0rxg2F96gwNgkpFjYSun4TWf2s=
AllowedIPs = 0.0.0.0/0
Endpoint = 185.107.56.22:51820
